version: "3.9"

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dbt:
    container_name: dbt
    build: .
    image: dbt
    volumes:
      - ./:/usr/src/dbt

